FROM alpine:3.22

RUN apk add --update --no-cache \
git \
curl \
bash \
zip \
python3 \
docker-cli

RUN curl -sSL https://sdk.cloud.google.com | bash

ENV PATH $PATH:/root/google-cloud-sdk/bin

CMD [ "bin/bash"]