FROM alpine:3.22

RUN apk add --update --no-cache \
git \
jq \
curl \
tar \
bash \
zip \
python3 \
py3-pip \
docker-cli  

RUN curl -sSL https://sdk.cloud.google.com | bash

ENV PATH $PATH:/root/google-cloud-sdk/bin

RUN pip install --upgrade pip --break-system-packages

CMD [ "bin/bash"]