FROM alpine:3.22

RUN apk add --update --no-cache \
git \
curl \
bash \
zip \
docker-cli  

RUN curl -sSL https://sdk.cloud.google.com | bash

ENV PATH $PATH:/root/google-cloud-sdk/bin

RUN pip install --upgrade pip --break-system-packages

CMD [ "bin/bash"]